### PR TITLE
Replaced fileSystem moving around with requireg

### PR DESCRIPTION
**Pull request by warang580**
> Remove the need for moving generators (especially globally installed generators) into a temporary directory before require()-ing.

I simplified `stimpak` using [requireg](https://www.npmjs.com/package/requireg). All tests are at green !

Note: In `source/spec/cli/stimpak.cli.helper.js`, I replaced `temporaryNodeModulesDirectoryPath` with `globalNodeModulesDirectoryPath` because, as I understand it, generators need to be installed globally and they would be installed in the global directory, not in the temporary one  (they were not found with requireg in the last one).

I think it covers every point you wanted, but check `source/spec/cli/stimpak.cli.helper.js` to be sure I did a correct change.

### CODE REVIEW

**Comment by warang580** [comment]
Travis-CI fails on Node.js v0.10 version because `child_process.execSync` doesn't exist (yet).

**Comment by dcrockwell** [comment]
Don't worry about the 0.10, we'll take care of that in another PR.

I'm checking over the code now :)

**Comment by dcrockwell** [comment]
You probably want to pull from the latest develop now to avoid merge nightmares later

**Comment by dcrockwell** [comment]
You need to see this. It kind of changes everything and invalidates the work in this PR: https://github.com/FreeAllMedia/stimpak/issues/13

**Pull request closed without merging**
